### ISSUE TITLE
Update to type-coverage 2.23.0 and support files feature

### ISSUE THREAD

**Issue by StaRenn** [alexcanessa/typescript-coverage-report#100]
**Is your feature request related to a problem? Please describe.**
type-coverage 2.23.0 added a feature to check only passed files, that could be helpful for lint-staged,
but type-coverage by itself doesn't show failed files and their coverage, only total

**Describe the solution you'd like**
Update to type-coverage 2.23.0 and add support of checking only passed files

**Comment by alexcanessa** [comment]
@StaRenn oh nice! Yes agree we should upgrade ASAP. Any chance you got time to update it?

**Comment by StaRenn** [comment]
#101

**Comment by alexcanessa** [comment]
@StaRenn I released `0.7.0` which incudes this. Thank you :)
