### ISSUE TITLE
Suggestion: Add Issue Templates

### ISSUE THREAD

**Issue by tsaiDavid** [alexcanessa/typescript-coverage-report#2]
@alexcanessa - what do you think about adding [Issue Templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)?

**Comment by alexcanessa** [comment]
@tsaiDavid yes for sure!

**Comment by alexcanessa** [comment]
@tsaiDavid done ✅ (feedback welcome 😂)
