### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by OmgImAlexis** [alexcanessa/typescript-coverage-report#21]
No ci task is setup and the master branch has new commits which aren't published to npm. Right now I have to delete the directory for `coverage-ts` and make a new one before the script can run because of the `ENOTEMPTY` error that's thrown.

**Comment by alexcanessa** [comment]
@OmgImAlexis yes I'm doing it in the next few hours. I'll keep you posted on this issue.

**Comment by alexcanessa** [comment]
@OmgImAlexis 0.1.3 is published. Have a look a let me know :)

**Comment by OmgImAlexis** [comment]
No issues here. ^_^ Good job.
