### ISSUE TITLE
Bug: No way to ignore files

### ISSUE THREAD

**Issue by OmgImAlexis** [alexcanessa/typescript-coverage-report#24]
**Describe the bug**
The `--ignore-files` flag can't be used even though `coverage-report` supports it.

**Comment by alexcanessa** [comment]
👍 Yes, should be straight-forward to implement as well.
Thanks.

**Comment by alexcanessa** [comment]
@OmgImAlexis this has been released as part of [v0.3.0](https://github.com/alexcanessa/typescript-coverage-report/releases/tag/0.3.0)
