### ISSUE TITLE
Publish a version with the new JSON reporter?

### ISSUE THREAD

**Issue by serhalp** [alexcanessa/typescript-coverage-report#28]
Hello,

I see a JSON reporter was added a couple months ago: https://github.com/alexcanessa/typescript-coverage-report/commit/6bb454deeb7a3bb56a3a551d557ae112ffa8a4f1.

No version was published to the NPM registry with this feature. Could you please publish one so that I can use the JSON report? Thank you!

**Comment by lakshyaranganath** [comment]
Bumping this, could we have this released soon? I'd like to use the JSON reporter as-well.

Thanks!

**Comment by alexlawrence** [comment]
The last comment on this is already quite old. Any news on this one? Thank you!

**Comment by OmgImAlexis** [comment]
@alexlawrence can you please publish a new version to npm if you've already done so can this issue please be closed.

**Comment by alexlawrence** [comment]
@OmgImAlexis I think you meant @alexcanessa.

**Comment by OmgImAlexis** [comment]
Oops. Sorry on mobile.

**Comment by alexcanessa** [comment]
@OmgImAlexis sorry took a long time, the JSON reporter is on version 0.2.0 now 🎉
