### ISSUE TITLE
Bug: Add support for optional variables

### ISSUE THREAD

**Issue by OmgImAlexis** [alexcanessa/typescript-coverage-report#30]
`profile?.username` is what's causing the issue.

```ts
        await redis.publish(`user:${profile?.username}.servers`, JSON.stringify(usersServers));
```

<img width="925" alt="Screen Shot 2020-11-02 at 3 05 28 pm" src="https://user-images.githubusercontent.com/6525926/97830436-dd0f7680-1d1c-11eb-8756-39300c12f4c4.png">

Removing the `?` allows the page to render correctly.

<img width="845" alt="Screen Shot 2020-11-02 at 3 06 18 pm" src="https://user-images.githubusercontent.com/6525926/97830471-00d2bc80-1d1d-11eb-965f-97b8f5d0a5b8.png">

**Comment by alexcanessa** [comment]
@OmgImAlexis the support should depend on the TS configuration you use. The problem here is that `error` isn't typed.

**Comment by OmgImAlexis** [comment]
No... read the issue again. The issue is with the highlighting.

**Comment by alexcanessa** [comment]
Oh sorry, I see @OmgImAlexis.

I'm afraid there isn't much we can do: the highlight is done using **codemirror**.

There is a newer version that I'll try to use and get in the next release. It doesn't seem to update conditional annotations for JS, but we can 🤞 and keep this open until they fix it.

Thanks for raising it.

**Comment by alexcanessa** [comment]
@OmgImAlexis just checked and it does 🎉 

Going to release this in `0.3.0` in a few minutes.

**Comment by alexcanessa** [comment]
@OmgImAlexis [released](https://github.com/alexcanessa/typescript-coverage-report/releases/tag/0.3.0).
