### ISSUE TITLE
Suggestion: Use all options from type-coverage package

### ISSUE THREAD

**Issue by alexcanessa** [alexcanessa/typescript-coverage-report#33]

**Comment by alexcanessa** [comment]
Closed by #31

**Comment by alexcanessa** [comment]
@dankv this is the [new release](https://github.com/alexcanessa/typescript-coverage-report/releases/tag/0.3.1). Are you able to test it and see if it's how you would expect it to be?

**Comment by danvk** [comment]
@alexcanessa confirmed the fix. Thanks for the quick turnaround!

**Comment by dignite** [comment]
@alexcanessa 🎉 

This is great, I was hoping for the [`ignoreCatch` flag in `type-coverage-core`](https://github.com/plantain-00/type-coverage/blob/162532c6ebb0bfce9704b8608e9d0591503164b9/packages/core/src/interfaces.ts#L45) to be supported as well, from what I can see [in the code it is not](https://github.com/alexcanessa/typescript-coverage-report/blob/f779a4f27ff7f5a44e485a5c4a63652f0170afe0/src/lib/getCoverage.ts#L23).

Is that correct? Considering attempting to add support myself but not sure if I will find the time in the near future.

**Comment by alexcanessa** [comment]
@dignite you're right, I think I thought that `enableCache = false` would be the same as `ignoreCache`. Is it not?

**Comment by dignite** [comment]
> @dignite you're right, I think I thought that `enableCache = false` would be the same as `ignoreCache`. Is it not?

Hi! Sorry for the short answer that follows, busy day :(

The flag I'm talking about is ignore catch, which ignores type coverage on the error parameter in catch clauses, which has to be `any` by design.

**Comment by alexcanessa** [comment]
@dignite ok great!

I've created an issue #40, it should be pretty straight forward to implement.
