### ISSUE TITLE
Bug: files with 0 count show invalid percentage

### ISSUE THREAD

**Issue by alexcanessa** [alexcanessa/typescript-coverage-report#4]
**Describe the bug**
When the `totalCount` is `0`, the percentage is `NaN%`.
This happens because any number divided by 0 is `NaN`.

**To Reproduce**
Run the script on a file that doesn't have anything to get typed (like JSON files, apparently analysed by `tsc`).

**Actual behaviour**

**Expected behaviour**
Show `N/D` or `100%`?

**Environment**
 - Tool version: 0.1.1

**Comment by tsaiDavid** [comment]
@alexcanessa - funny enough, just noticed this issue too in my company's Next.js project - as it generates `next-env.d.ts` automatically. Adding something like this:

```tsx
/* next-env.d.ts */

/// <reference types="next" />
/// <reference types="next/types/global" />
```

**Comment by OmgImAlexis** [comment]
Having the same issue myself with barrel files.

```ts
// created from 'create-ts-index'

export * from './apikeys';
export * from './array';
export * from './debug';
export * from './disks';
```
