### ISSUE TITLE
Suggestion: Use ignoreCatch option from type-coverage

### ISSUE THREAD

**Issue by alexcanessa** [alexcanessa/typescript-coverage-report#40]
**Is your feature request related to a problem? Please describe.**
The `ignoreCatch ` option is not currently implemented.

**Describe the solution you'd like**
Enable the option.

**Additional context**
This feature was missing from #33 and reported by https://github.com/alexcanessa/typescript-coverage-report/issues/33#issuecomment-729946011

**Comment by dignite** [comment]
Correction: `ignoreCatch` not `ignoreCache` ❤️

**Comment by alexcanessa** [comment]
> Correction: `ignoreCatch` not `ignoreCache` ❤️

Oops.

**Comment by dignite** [comment]
Hey! Eagerly awaiting a release containing this feature :) @alexcanessa

**Comment by alexcanessa** [comment]
@dignite oh sorry, I thought I did. I'll release later this afternoon

**Comment by alexcanessa** [comment]
@dignite it's in. `0.4.0` is out
