### ISSUE TITLE
Bug: No TS4 support thus "Unknown compiler option" Errors

### ISSUE THREAD

**Issue by Jasperrr91** [alexcanessa/typescript-coverage-report#49]
**Describe the bug**
Typescript-coverage-report seems to run on TS ^3 instead of TS 4 released last August. Thus using new compiler options like `jsxFragmentFactory` will cause the coverage report script not to work.

**To Reproduce**
Use compiler options introduced in TS 4 like `jsxFragmentFactory`.

**Expected behaviour**
Expected a normal coverage output.

**Screenshots**
If it regards the HTML report, you might want to take a few screenshots.

**Environment**
 - Tool version: `^0.4.0`
 - OS: macOs Big Sur (11.1)
 - Node version: V12.19
 - Browser (if applicable): [e.g. chrome, safari]

**Additional context**

**Comment by Jasperrr91** [comment]
So apparently this was fixed in https://github.com/alexcanessa/typescript-coverage-report/pull/44 but not properly included in the 0.4.0 release: https://github.com/alexcanessa/typescript-coverage-report/releases/tag/0.4.0.

**Comment by alexcanessa** [comment]
@Jasperrr91 yes it was meant to go in `0.5.0` which was never released. I'll add release tomorrow.

**Comment by Jasperrr91** [comment]
Awesome, thanks @alexcanessa!

**Comment by alexcanessa** [comment]
@Jasperrr91 `0.5.0` released, let me know if it works.

**Comment by alexcanessa** [comment]
@Jasperrr91 is this working? I'd like to close it if yes.
