### ISSUE TITLE
Bug: typeCoverage config not working

### ISSUE THREAD

**Issue by tsaiDavid** [alexcanessa/typescript-coverage-report#5]
**Describe the bug**

In the provided example, I am expecting the tool to fail since the expected actual coverage is `92%`, and my provided minimum is `99%`. This works when using the CLI option, but not when using the `typeCoverage` property in `package.json`.

Provided config:
```json
  "typeCoverage": {
    "atLeast": 99
  },
```

CLI output when using `typeCoverage` (wrong behavior):

![image](https://user-images.githubusercontent.com/12259854/77589053-3e7a8780-6ea8-11ea-91a6-132d6914b23f.png)

CLI output when using `--threshold` option (expected behavior):
![image](https://user-images.githubusercontent.com/12259854/77589317-adf07700-6ea8-11ea-9957-d8eadd80d0cc.png)

As a side note, noticed the `cache` option to generate `.ts-coverage` does not seem to work either, I suspect it may be related.

**To Reproduce**
See: https://codesandbox.io/s/crazy-sound-ujkcu

You can export the CodeSandbox as a zip and run locally after `yarn install`.

![image](https://user-images.githubusercontent.com/12259854/77588611-73d2a580-6ea7-11ea-98fd-7eec9082f9e5.png)

**Expected behaviour**
Using `typeCoverage` should have parity with `typescript-coverage-report` CLI options.

**Screenshots**
N/A

**Environment**
 - Tool version: 0.1.1
 - OS: MacOS 10.15.3
 - Node version: 12 LTS
 - Browser (if applicable): [e.g. chrome, safari]

**Additional context**
N/A

**Comment by tsaiDavid** [comment]
@alexcanessa - I can try taking a stab at this

**Comment by tsaiDavid** [comment]
@alexcanessa - PR is now open, looks like it will need some more work if you'd also like to see the ability to essentially "pass-through" any options that `type-coverage` supports.

**Comment by alexcanessa** [comment]
Nice.

For now, it only gets `strict` and `debug`, manually set. Otherwise, that's the complete Option type:

```typescript
interface LintOptions {
    debug: boolean;
    files?: string[];
    oldProgram?: ts.Program;
    strict: boolean;
    enableCache: boolean;
    ignoreCatch: boolean;
    ignoreFiles?: string | string[];
    fileCounts: boolean;
    absolutePath?: boolean;
}
```

I think we could have a separate issue for tracking separate options 🤷‍♂

**Comment by tsaiDavid** [comment]
Gotcha, that's not a bad idea - would make it easier to incrementally add those in if people seem to want to use it. Feel free to make changes where needed to this PR too!

Side note: How do you feel about adding [all-contributors](https://github.com/all-contributors/all-contributors)? 😬

**Comment by alexcanessa** [comment]
@tsaiDavid ha of course

**Comment by alexcanessa** [comment]
@all-contributors add @tsaiDavid for bug

**Comment by danvk** [comment]
+1 to this! I added an `ignoreUnread` option to `type-coverage` recently and would like to use it with typescript-coverage-report.

**Comment by alexcanessa** [comment]
@danvk I just released this as part of [v0.3.0](https://github.com/alexcanessa/typescript-coverage-report/releases/tag/0.3.0)

**Comment by danvk** [comment]
Hi @alexcanessa I tried the `ignoreUnread` option this morning and I'm not sure it's working.

In `package.json`:

```json
{
  "typeCoverage": {
    "ignoreCatch": true,
    "ignoreUnread": true
  }
}
```

If I run:

```ts
$ yarn type-coverage
58871 / 59260 99.34%
```

But with `type-coverage-report`, I see:

![image](https://user-images.githubusercontent.com/98301/98564169-0890e480-227a-11eb-947f-99901c07cbc3.png)

The difference is because `ignore-unread` isn't being used:

![image](https://user-images.githubusercontent.com/98301/98564278-29f1d080-227a-11eb-901e-0bf271757260.png)

When I run `yarn type-coverage` with `--details`, those symbols are not included (because they aren't read).

```
$ yarn type-coverage --version
Version: 2.14.0
$ yarn typescript-coverage-report --version
0.3.0
```

**Comment by alexcanessa** [comment]
@danvk interesting. That's quite weird.

**Comment by alexcanessa** [comment]
@danvk I got the problem, forgot to add one thing 🙈 

Please track this on #33
