### ISSUE TITLE
Integration with Unit Tests? 

### ISSUE THREAD

**Issue by stealthrabbi** [alexcanessa/typescript-coverage-report#62]
It doesn't seem like this coverage tool takes in to account unit test files, or really, what hte coverage is based on. Is it just baed on what methods are called by other methods? I'd like to be able to configure this to report on what methods / lines my unit test files are covering.

**Comment by alexcanessa** [comment]
Hello @stealthrabbi 

This package is built on top of https://github.com/plantain-00/type-coverage, which creates the actual coverage which this tool then displays in a report.

Please move this issue to that repo.
